import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateEvidenceReport(Map<String, dynamic> escrowData, String escrowId) async {
    final pdf = pw.Document();

    final date = DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now());

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(level: 0, child: pw.Text("AMANAH-BOT LEGAL EVIDENCE REPORT", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18))),
                pw.SizedBox(height: 10),
                pw.Text("Generated on: $date"),
                pw.Text("Escrow ID: $escrowId"),
                pw.Divider(),
                pw.SizedBox(height: 20),
                
                pw.Text("TRANSACTION DETAILS", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Bullet(text: "Item: ${escrowData['item']}"),
                pw.Bullet(text: "Price: RM ${escrowData['price']}"),
                pw.Bullet(text: "Status: ${escrowData['status']}"),
                pw.Bullet(text: "Tracking: ${escrowData['tracking_number']}"),
                pw.SizedBox(height: 20),

                pw.Text("AI FORENSIC VERDICT", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text("AI Verified: ${escrowData['ai_verified']}"),
                pw.Text("Receipt Fingerprint (SHA-256): ${escrowData['receipt_hash'] ?? 'N/A'}"),
                pw.SizedBox(height: 20),

                pw.Text("IMMUTABLE AUDIT LOGS", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                ...(escrowData['logs'] as List<dynamic>? ?? []).map((log) => pw.Text("- $log", style: const pw.TextStyle(fontSize: 10))),
                
                pw.Spacer(),
                pw.Divider(),
                pw.Align(
                  alignment: pw.Alignment.center,
                  child: pw.Text("This document is an immutable record of a secure agentic escrow transaction. Generated by Amanah-Bot Core Protocol.", style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
                )
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
