name: amanah_ui
description: "Amanah-Bot EaaS Portal"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  http_parser: ^4.0.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  google_fonts: ^6.0.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
